name: CI

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ~/jhaemin/game-of-life-3d
            git reset --hard
            git fetch
            git pull
            cd ~/jhaemin/game-of-life-3d/wasm
            wasm-pack build
            cd ~/jhaemin/game-of-life-3d
            npm install
            npm run build
            pm2 restart gol3d
